# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bab3d25d2c2b4c455b6ced923edd2184ab0754d4501330834bb729ac5fbb95a93ef282b550cf550d2aaef409ab0a9795da85e602e0d6f2d00ec1ae1fa02d2dc9

test:
  secret_key_base: d780505e3ba4d85c7f895e14c6e2e4e1dcf8bf9b5107154c3103b244e59de87b7657f30961f65ee960a35f3c091c09bb7636f3987ab61f73f9f62a0c35bc9fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
